# Generated by Django 4.2.30 on 2026-06-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True)),
                ('image_base64', models.TextField(blank=True, help_text='Base64 encoded banner image')),
                ('image_url', models.URLField(blank=True, help_text='External image URL (alternative to base64)')),
                ('link_type', models.CharField(choices=[('TOURNAMENT', 'Tournament'), ('VENUE', 'Venue'), ('OPEN_MATCH', 'Open Match'), ('EXTERNAL', 'External URL'), ('NONE', 'No Link')], default='NONE', max_length=20)),
                ('link_id', models.CharField(blank=True, help_text='ID of linked tournament, venue, or match', max_length=100)),
                ('external_url', models.URLField(blank=True, help_text='For EXTERNAL link type')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Lower number = shown first')),
                ('start_date', models.DateField(blank=True, help_text='Show banner from this date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Hide banner after this date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner Ad',
                'verbose_name_plural': 'Banner Ads',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
