# Generated by Django 4.2.30 on 2026-06-16 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(max_length=100, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_signature', models.CharField(blank=True, max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in INR', max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=5)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='CREATED', max_length=20)),
                ('payment_for', models.CharField(choices=[('BOOKING', 'Court Booking'), ('OPEN_MATCH', 'Open Match'), ('TOURNAMENT', 'Tournament Entry'), ('EQUIPMENT', 'Equipment Rental')], default='BOOKING', max_length=20)),
                ('booking_id', models.IntegerField(blank=True, help_text='bookings.Booking ID', null=True)),
                ('open_match_id', models.IntegerField(blank=True, help_text='tournaments.OpenMatch ID', null=True)),
                ('tournament_id', models.IntegerField(blank=True, help_text='tournaments.Tournament ID', null=True)),
                ('notes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='players.player')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
