# Generated by Django 4.2.27 on 2026-01-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_court_count_court_surface_type_venue_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='venue',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='venue',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
