# Generated by Django 6.0 on 2026-01-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_venue_aadhar_number_venue_gst_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='aadhar_document',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='gst_document',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='venue',
            name='pan_document',
            field=models.TextField(blank=True),
        ),
    ]
