# Generated by Django 6.0 on 2026-02-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_venue_aadhar_document_venue_gst_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='status',
            field=models.CharField(choices=[('PRE_REGISTERED', 'Pre-Registered'), ('REGISTERED', 'Registered'), ('REJECTED', 'Rejected')], default='PRE_REGISTERED', max_length=20),
        ),
    ]
