#!/bin/bash

echo "=================================================="
echo "  GoAthlete - Quick Start All Services"
echo "=================================================="
echo ""
echo "This script will help you run all services."
echo "Each service will need its own terminal."
echo ""
echo "Please run these commands in separate terminals:"
echo ""
echo "Terminal 1 (Backend):"
echo "  ./run_backend.sh"
echo ""
echo "Terminal 2 (Admin Web):"
echo "  ./run_admin_web.sh"
echo ""
echo "Terminal 3 (Executive App - Web):"
echo "  ./run_executive_web.sh"
echo ""
echo "=================================================="
echo "  Access URLs"
echo "=================================================="
echo ""
echo "Backend API:        http://localhost:8000"
echo "Django Admin:       http://localhost:8000/admin"
echo "Admin Web App:      http://localhost:5173"
echo "Executive App:      http://localhost:8081"
echo ""
echo "=================================================="
echo "  Credentials"
echo "=================================================="
echo ""
echo "Django Admin:"
echo "  Email:    admin@goathlete.org.in"
echo "  Password: admin123"
echo ""
echo "Admin Web App:"
echo "  Email:    admin1@goathlete.org.in"
echo "  Password: admin123"
echo ""
echo "Executive App:"
echo "  Email:    exec1@goathlete.org.in"
echo "  Password: exec123"
echo ""
echo "=================================================="

