# Generated by Django 6.0 on 2026-02-01 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0004_venue_aadhar_document_venue_gst_document_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this vendor admin can login.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_admin_profile', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(help_text='Venue managed by this admin', on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='venues.venue')),
            ],
            options={
                'verbose_name': 'Vendor Admin',
                'verbose_name_plural': 'Vendor Admins',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('permissions', models.JSONField(blank=True, default=dict, help_text="Partner-specific permissions: {'can_block_slots': True, 'can_export_reports': False, ...}")),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this partner can login.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(help_text='Vendor admin who manages this partner', on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='partners.vendoradmin')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_partner_profile', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(help_text='Venue where this partner works', on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='venues.venue')),
            ],
            options={
                'verbose_name': 'Vendor Partner',
                'verbose_name_plural': 'Vendor Partners',
                'ordering': ['-created_at'],
            },
        ),
    ]
