# Generated by Django 6.0 on 2026-02-01 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('venues', '0004_venue_aadhar_document_venue_gst_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_id', models.CharField(editable=False, help_text='Auto-generated: TN20260201001', max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('sport_type', models.CharField(help_text='Cricket, Football, Badminton, etc.', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('max_teams', models.IntegerField(default=8)),
                ('team_size', models.IntegerField(default=11, help_text='Players per team')),
                ('match_format', models.CharField(help_text="e.g., '20 overs', '90 minutes', 'Best of 3'", max_length=100)),
                ('scoring_config', models.JSONField(blank=True, default=dict, help_text="Sport-specific configuration: {'overs': 20, 'players_per_side': 11, ...}")),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UPCOMING', 'Upcoming'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('total_matches', models.IntegerField(default=0)),
                ('total_teams', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('rules', models.TextField(blank=True)),
                ('prize_details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_tournaments', to='players.player')),
                ('venue', models.ForeignKey(blank=True, help_text='Optional - venue where tournament is held', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to='venues.venue')),
            ],
            options={
                'verbose_name': 'Tournament',
                'verbose_name_plural': 'Tournaments',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.TextField(blank=True, help_text='Base64 encoded image')),
                ('matches_played', models.IntegerField(default=0)),
                ('matches_won', models.IntegerField(default=0)),
                ('matches_lost', models.IntegerField(default=0)),
                ('matches_drawn', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captained_teams', to='players.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['-points', '-matches_won'],
                'unique_together': {('tournament', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(editable=False, help_text='Auto-generated: MT20260201001', max_length=20, unique=True)),
                ('match_number', models.IntegerField(help_text='Match 1, Match 2, etc.')),
                ('match_date', models.DateField()),
                ('match_time', models.TimeField()),
                ('scorecard', models.JSONField(blank=True, default=dict, help_text='Sport-specific scorecard data')),
                ('result_summary', models.CharField(blank=True, help_text="e.g., 'Team A won by 50 runs'", max_length=255)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('umpire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='umpired_matches', to='players.player')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='venues.venue')),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team_a', to='tournaments.team')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team_b', to='tournaments.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='tournaments.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'ordering': ['match_date', 'match_time'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats', models.JSONField(default=dict, help_text="Sport-specific stats: {'runs': 50, 'wickets': 2, 'goals': 1, ...}")),
                ('performance_rating', models.DecimalField(blank=True, decimal_places=1, help_text='Performance rating out of 10', max_digits=3, null=True)),
                ('is_man_of_match', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_performances', to='tournaments.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_stats', to='players.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_performances', to='tournaments.team')),
            ],
            options={
                'verbose_name': 'Performance Stats',
                'verbose_name_plural': 'Performance Stats',
                'ordering': ['-created_at'],
                'unique_together': {('player', 'match')},
            },
        ),
        migrations.CreateModel(
            name='TeamPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jersey_number', models.IntegerField(blank=True, null=True)),
                ('role', models.CharField(blank=True, help_text='e.g., Batsman, Bowler, All-rounder, Goalkeeper, etc.', max_length=100)),
                ('is_captain', models.BooleanField(default=False)),
                ('is_vice_captain', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='players.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_players', to='tournaments.team')),
            ],
            options={
                'verbose_name': 'Team Player',
                'verbose_name_plural': 'Team Players',
                'ordering': ['jersey_number'],
                'unique_together': {('team', 'player')},
            },
        ),
    ]
