# Generated by Django 6.0 on 2026-02-02 17:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='Unique sport code (e.g., CRICKET, FOOTBALL)', max_length=20, unique=True)),
                ('icon', models.CharField(help_text='Emoji or icon identifier', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sport',
                'verbose_name_plural': 'Sports',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='sport_type',
        ),
        migrations.AddField(
            model_name='tournament',
            name='sport',
            field=models.ForeignKey(blank=True, help_text='Sport type - determines scoreboard template', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='tournaments.sport'),
        ),
        migrations.CreateModel(
            name='SportScoreboardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_roles', models.JSONField(default=list, help_text="List of player roles: ['batsman', 'bowler', 'allrounder', 'wicketkeeper']")),
                ('team_structure', models.JSONField(default=dict, help_text="Team config: {'players_per_team': 11, 'innings': true, 'substitutes_allowed': 3}")),
                ('scoring_fields', models.JSONField(default=list, help_text="Main scoring fields: ['runs', 'wickets', 'overs'] or ['goals', 'assists']")),
                ('player_stat_fields', models.JSONField(default=list, help_text="Player stats: ['runs', 'balls', 'fours', 'sixes', 'wickets'] or ['goals', 'assists', 'yellow_cards']")),
                ('match_event_types', models.JSONField(default=list, help_text="Events: ['run', 'wicket', 'wide', 'no_ball'] or ['goal', 'foul', 'corner']")),
                ('award_rules', models.JSONField(default=dict, help_text="Award definitions: {'orange_cap': {'stat': 'runs', 'type': 'max'}, 'purple_cap': {'stat': 'wickets', 'type': 'max'}}")),
                ('ui_config', models.JSONField(blank=True, default=dict, help_text='UI-specific config: colors, layouts, display order')),
                ('validation_rules', models.JSONField(blank=True, default=dict, help_text='Validation rules for scoring: min/max values, dependencies')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scoreboard_template', to='tournaments.sport')),
            ],
            options={
                'verbose_name': 'Sport Scoreboard Template',
                'verbose_name_plural': 'Sport Scoreboard Templates',
            },
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(help_text="Event type from sport template: 'run', 'wicket', 'goal', 'foul', etc.", max_length=50)),
                ('event_data', models.JSONField(default=dict, help_text="Event-specific data: {'runs': 4, 'ball_number': 15} or {'minute': 45, 'assist_by': 'player_id'}")),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('match_time', models.CharField(blank=True, help_text="Match time: '12.3 overs' or '45:30 minutes'", max_length=50)),
                ('sequence_number', models.IntegerField(default=0, help_text='Event sequence in match')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tournaments.match')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_events', to='players.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_events', to='tournaments.team')),
            ],
            options={
                'verbose_name': 'Match Event',
                'verbose_name_plural': 'Match Events',
                'ordering': ['match', 'sequence_number'],
                'indexes': [models.Index(fields=['match', 'sequence_number'], name='tournaments_match_i_99fca0_idx'), models.Index(fields=['event_type'], name='tournaments_event_t_13d833_idx')],
            },
        ),
        migrations.CreateModel(
            name='MatchScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_stats', models.JSONField(default=dict, help_text="Team stats: {'runs': 185, 'wickets': 6, 'overs': 20} or {'goals': 3, 'possession': 65}")),
                ('inning', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_batting', models.BooleanField(default=False, help_text='For cricket: is this team batting?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='tournaments.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to='tournaments.team')),
            ],
            options={
                'verbose_name': 'Match Score',
                'verbose_name_plural': 'Match Scores',
                'ordering': ['match', 'inning', 'team'],
                'unique_together': {('match', 'team', 'inning')},
            },
        ),
        migrations.CreateModel(
            name='PlayerMatchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats', models.JSONField(default=dict, help_text="Player stats: {'runs': 75, 'balls': 45, 'fours': 8, 'sixes': 3} or {'goals': 2, 'assists': 1}")),
                ('performance_rating', models.DecimalField(blank=True, decimal_places=1, help_text='Performance rating out of 10', max_digits=3, null=True)),
                ('is_man_of_match', models.BooleanField(default=False)),
                ('awards', models.JSONField(blank=True, default=list, help_text="List of awards: ['best_batsman', 'best_bowler']")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='tournaments.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_stats', to='players.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_match_stats', to='tournaments.team')),
            ],
            options={
                'verbose_name': 'Player Match Stats',
                'verbose_name_plural': 'Player Match Stats',
                'ordering': ['-created_at'],
                'unique_together': {('match', 'player')},
            },
        ),
    ]
