# Generated by Django 6.0 on 2026-03-15 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('tournaments', '0002_sport_remove_tournament_sport_type_tournament_sport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scoreboard', models.JSONField(blank=True, default=dict, help_text='Flexible sport-specific scoreboard: {teamA: {...}, teamB: {...}} or player scores')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_local_tournaments', to='players.player')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_tournaments', to='tournaments.sport')),
            ],
            options={
                'verbose_name': 'Local Tournament',
                'verbose_name_plural': 'Local Tournaments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocalTournamentParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('score', models.JSONField(blank=True, default=dict, help_text='Player-specific score data, structure depends on sport')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournaments.localtournament')),
            ],
            options={
                'verbose_name': 'Local Tournament Participant',
                'verbose_name_plural': 'Local Tournament Participants',
                'ordering': ['name'],
            },
        ),
    ]
