# Generated by Django 4.2.30 on 2026-06-16 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('venues', '0006_venue_latitude_venue_longitude'),
        ('tournaments', '0003_localtournament_localtournamentparticipant'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration_hours', models.DecimalField(decimal_places=1, default=1.0, max_digits=4)),
                ('total_spots', models.IntegerField()),
                ('price_per_player', models.DecimalField(decimal_places=2, max_digits=8)),
                ('skill_level', models.CharField(blank=True, help_text='e.g., Beginner, Intermediate, Advanced', max_length=50)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FULL', 'Full'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_open_matches', to='players.player')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='open_matches', to='tournaments.sport')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_matches', to='venues.venue')),
            ],
        ),
        migrations.CreateModel(
            name='OpenMatchPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(default='PENDING', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='tournaments.openmatch')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_open_matches', to='players.player')),
            ],
            options={
                'unique_together': {('match', 'player')},
            },
        ),
    ]
