# Generated by Django 6.0 on 2026-07-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_openmatch_openmatchplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='min_players',
            field=models.IntegerField(default=2, help_text='Total minimum players required to create a match (e.g. Cricket=22, Badminton singles=2)'),
        ),
    ]
