# Generated by Django 6.0 on 2026-07-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_sport_min_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localtournamentparticipant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
