# Generated by Django 6.0 on 2026-01-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this executive can login.'),
        ),
    ]
