# Generated by Django 6.0 on 2026-02-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_executive_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('EXECUTIVE', 'Executive'), ('VENDOR_ADMIN', 'Vendor Admin'), ('VENDOR_PARTNER', 'Vendor Partner'), ('PLAYER', 'Player')], default='EXECUTIVE', max_length=20),
        ),
    ]
