# Generated by Django 6.0 on 2026-02-02 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('hourly_count', models.IntegerField(default=0)),
                ('daily_count', models.IntegerField(default=0)),
                ('hourly_reset_at', models.DateTimeField()),
                ('daily_reset_at', models.DateTimeField()),
                ('hourly_limit', models.IntegerField(default=3)),
                ('daily_limit', models.IntegerField(default=10)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OTP Rate Limit',
                'verbose_name_plural': 'OTP Rate Limits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Phone number with country code', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('otp', models.CharField(max_length=6)),
                ('otp_hash', models.CharField(help_text='Hashed OTP for security', max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0, help_text='Number of verification attempts')),
                ('max_attempts', models.IntegerField(default=3)),
                ('twilio_sid', models.CharField(blank=True, help_text='Twilio message SID', max_length=100)),
                ('twilio_status', models.CharField(blank=True, help_text='Twilio delivery status', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'WhatsApp OTP',
                'verbose_name_plural': 'WhatsApp OTPs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'is_verified'], name='accounts_wh_phone_n_c73f34_idx'), models.Index(fields=['created_at'], name='accounts_wh_created_8bd41c_idx')],
            },
        ),
    ]
