# Generated by Django 6.0 on 2026-02-01 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('partners', '0001_initial'),
        ('players', '0001_initial'),
        ('venues', '0004_venue_aadhar_document_venue_gst_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bookings', to='partners.vendoradmin'),
        ),
        migrations.AddField(
            model_name='booking',
            name='created_by_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bookings', to='partners.vendorpartner'),
        ),
        migrations.AddField(
            model_name='booking',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='players.player'),
        ),
        migrations.AddField(
            model_name='booking',
            name='venue',
            field=models.ForeignKey(help_text='Denormalized for quick queries', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='venues.venue'),
        ),
        migrations.AddField(
            model_name='slotblock',
            name='blocked_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_slots', to='partners.vendoradmin'),
        ),
        migrations.AddField(
            model_name='slotblock',
            name='blocked_by_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_slots', to='partners.vendorpartner'),
        ),
        migrations.AddField(
            model_name='slotblock',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_slots', to='venues.court'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date', 'court'], name='bookings_bo_booking_291ee7_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['venue', 'booking_date'], name='bookings_bo_venue_i_2cffeb_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='bookings_bo_status_233e96_idx'),
        ),
        migrations.AddIndex(
            model_name='slotblock',
            index=models.Index(fields=['court', 'block_date'], name='bookings_sl_court_i_da56e2_idx'),
        ),
        migrations.AddIndex(
            model_name='slotblock',
            index=models.Index(fields=['is_active'], name='bookings_sl_is_acti_7c5cf5_idx'),
        ),
    ]
