# Generated by Django 6.0 on 2026-02-01 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique badge code', max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Emoji or icon name', max_length=50)),
                ('category', models.CharField(choices=[('TOURNAMENT', 'Tournament'), ('PERFORMANCE', 'Performance'), ('MILESTONE', 'Milestone'), ('SPECIAL', 'Special')], max_length=50)),
                ('requirements', models.JSONField(blank=True, default=dict, help_text="Requirements to earn this badge: {'min_tournaments': 1, ...}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('profile_image', models.TextField(blank=True, help_text='Base64 encoded image')),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True)),
                ('fitness_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('PROFESSIONAL', 'Professional')], default='BEGINNER', max_length=20)),
                ('total_matches', models.IntegerField(default=0)),
                ('total_tournaments', models.IntegerField(default=0)),
                ('total_wins', models.IntegerField(default=0)),
                ('badges', models.JSONField(blank=True, default=list, help_text="List of earned badge codes: ['first_tournament', 'winner', ...]")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_badges', to='players.badge')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to='players.player')),
            ],
            options={
                'verbose_name': 'Player Badge',
                'verbose_name_plural': 'Player Badges',
                'ordering': ['-earned_at'],
                'unique_together': {('player', 'badge')},
            },
        ),
    ]
